const killerPerks = [
    { id:"agitation", name:"Agitation", killerId:"trapper", tags:["hook","carry","pressure"] },
    { id:"brutal-strength", name:"Brutal Strength", killerId:"trapper", tags:["chase","generator","break"] },
    { id:"unnerving-presence", name:"Unnerving Presence", killerId:"trapper", tags:["terror-radius","skill-check","pressure"] },
    { id:"bloodhound", name:"Bloodhound", killerId:"wraith", tags:["tracking","chase"] },
    { id:"predator", name:"Predator", killerId:"wraith", tags:["tracking","chase"] },
    { id:"shadowborn", name:"Shadowborn", killerId:"wraith", tags:["utility","chase"] },
    { id:"enduring", name:"Enduring", killerId:"hillbilly", tags:["chase","stun"] },
    { id:"lightborn", name:"Lightborn", killerId:"hillbilly", tags:["anti-item","utility"] },
    { id:"tinkerer", name:"Tinkerer", killerId:"hillbilly", tags:["generator","info","stealth"] },
    { id:"a-nurses-calling", name:"A Nurse's Calling", killerId:"nurse", tags:["aura","healing","info"] },
    { id:"stridor", name:"Stridor", killerId:"nurse", tags:["tracking","info"] },
    { id:"thanatophobia", name:"Thanatophobia", killerId:"nurse", tags:["slowdown","injury"] },
    { id:"dying-light", name:"Dying Light", killerId:"shape", tags:["obsession","slowdown"] },
    { id:"play-with-your-food", name:"Play with Your Food", killerId:"shape", tags:["obsession","haste","chase"] },
    { id:"save-the-best-for-last", name:"Save the Best for Last", killerId:"shape", tags:["obsession","chase","basic-attack"] },
    { id:"hex-devour-hope", name:"Hex: Devour Hope", killerId:"hag", tags:["hex","hook","exposed"] },
    { id:"hex-ruin", name:"Hex: Ruin", killerId:"hag", tags:["hex","regression","slowdown"] },
    { id:"hex-the-third-seal", name:"Hex: The Third Seal", killerId:"hag", tags:["hex","blindness","pressure"] },
    { id:"monitor-and-abuse", name:"Monitor & Abuse", killerId:"doctor", tags:["terror-radius","stealth","chase"] },
    { id:"overcharge", name:"Overcharge", killerId:"doctor", tags:["generator","regression","skill-check"] },
    { id:"overwhelming-presence", name:"Overwhelming Presence", killerId:"doctor", tags:["terror-radius","anti-item"] },
    { id:"beast-of-prey", name:"Beast of Prey", killerId:"huntress", tags:["chase","stealth"] },
    { id:"hex-huntress-lullaby", name:"Hex: Huntress Lullaby", killerId:"huntress", tags:["hex","skill-check","pressure"] },
    { id:"territorial-imperative", name:"Territorial Imperative", killerId:"huntress", tags:["aura","basement","info"] },
    { id:"barbecue-and-chilli", name:"Barbecue & Chilli", killerId:"cannibal", tags:["aura","hook","info"] },
    { id:"franklins-demise", name:"Franklin's Demise", killerId:"cannibal", tags:["anti-item","basic-attack"] },
    { id:"knock-out", name:"Knock Out", killerId:"cannibal", tags:["slug","basic-attack","pressure"] },
    { id:"blood-warden", name:"Blood Warden", killerId:"nightmare", tags:["endgame","hook","gate"] },
    { id:"fire-up", name:"Fire Up", killerId:"nightmare", tags:["endgame","utility"] },
    { id:"remember-me", name:"Remember Me", killerId:"nightmare", tags:["endgame","obsession","gate"] },
    { id:"hangmans-trick", name:"Hangman's Trick", killerId:"pig", tags:["hook","info"] },
    { id:"make-your-choice", name:"Make Your Choice", killerId:"pig", tags:["hook","exposed","pressure"] },
    { id:"surveillance", name:"Surveillance", killerId:"pig", tags:["generator","info","regression"] },
    { id:"bamboozle", name:"Bamboozle", killerId:"clown", tags:["chase","vault"] },
    { id:"coulrophobia", name:"Coulrophobia", killerId:"clown", tags:["terror-radius","healing","slowdown"] },
    { id:"pop-goes-the-weasel", name:"Pop Goes the Weasel", killerId:"clown", tags:["hook","generator","regression"] },
    { id:"hex-haunted-ground", name:"Hex: Haunted Ground", killerId:"spirit", tags:["hex","exposed","pressure"] },
    { id:"rancor", name:"Rancor", killerId:"spirit", tags:["obsession","endgame","exposed"] },
    { id:"spirit-fury", name:"Spirit Fury", killerId:"spirit", tags:["chase","pallet","stun"] },
    { id:"discordance", name:"Discordance", killerId:"legion", tags:["generator","info"] },
    { id:"iron-maiden", name:"Iron Maiden", killerId:"legion", tags:["locker","exposed","info"] },
    { id:"mad-grit", name:"Mad Grit", killerId:"legion", tags:["carry","hook","pressure"] },
    { id:"corrupt-intervention", name:"Corrupt Intervention", killerId:"plague", tags:["early-game","slowdown","block"] },
    { id:"dark-devotion", name:"Dark Devotion", killerId:"plague", tags:["obsession","stealth","terror-radius"] },
    { id:"infectious-fright", name:"Infectious Fright", killerId:"plague", tags:["terror-radius","info","snowball"] },
    { id:"furtive-chase", name:"Furtive Chase", killerId:"ghost-face", tags:["obsession","hook","stealth"] },
    { id:"im-all-ears", name:"I'm All Ears", killerId:"ghost-face", tags:["aura","chase","info"] },
    { id:"thrilling-tremors", name:"Thrilling Tremors", killerId:"ghost-face", tags:["generator","block","info"] },
    { id:"cruel-limits", name:"Cruel Limits", killerId:"demogorgon", tags:["generator","chase","vault"] },
    { id:"mindbreaker", name:"Mindbreaker", killerId:"demogorgon", tags:["generator","exhaustion","pressure"] },
    { id:"surge", name:"Surge", killerId:"demogorgon", tags:["generator","regression","basic-attack"] },
    { id:"blood-echo", name:"Blood Echo", killerId:"oni", tags:["hook","injury","exhaustion"] },
    { id:"nemesis", name:"Nemesis", killerId:"oni", tags:["obsession","chase","aura"] },
    { id:"zanshin-tactics", name:"Zanshin Tactics", killerId:"oni", tags:["aura","chase","info"] },
    { id:"dead-mans-switch", name:"Dead Man's Switch", killerId:"deathslinger", tags:["hook","generator","block"] },
    { id:"gearhead", name:"Gearhead", killerId:"deathslinger", tags:["generator","aura","info"] },
    { id:"hex-retribution", name:"Hex: Retribution", killerId:"deathslinger", tags:["hex","aura","totem"] },
    { id:"deathbound", name:"Deathbound", killerId:"executioner", tags:["healing","tracking","oblivious"] },
    { id:"forced-penance", name:"Forced Penance", killerId:"executioner", tags:["protection-hit","pressure"] },
    { id:"trail-of-torment", name:"Trail of Torment", killerId:"executioner", tags:["generator","stealth"] },
    { id:"dragons-grip", name:"Dragon's Grip", killerId:"blight", tags:["generator","exposed","trap"] },
    { id:"hex-blood-favour", name:"Hex: Blood Favour", killerId:"blight", tags:["hex","chase","pallet"] },
    { id:"hex-undying", name:"Hex: Undying", killerId:"blight", tags:["hex","totem","support"] },
    { id:"coup-de-grace", name:"Coup de Grace", killerId:"twins", tags:["chase","endgame","lunge"] },
    { id:"hoarder", name:"Hoarder", killerId:"twins", tags:["anti-item","info"] },
    { id:"oppression", name:"Oppression", killerId:"twins", tags:["generator","regression","skill-check"] },
    { id:"hex-crowd-control", name:"Hex: Crowd Control", killerId:"trickster", tags:["hex","chase","vault"] },
    { id:"no-way-out", name:"No Way Out", killerId:"trickster", tags:["endgame","hook","gate"] },
    { id:"starstruck", name:"Starstruck", killerId:"trickster", tags:["carry","terror-radius","exposed"] },
    { id:"eruption", name:"Eruption", killerId:"nemesis", tags:["generator","regression","down"] },
    { id:"hysteria", name:"Hysteria", killerId:"nemesis", tags:["injury","stealth","oblivious"] },
    { id:"lethal-pursuer", name:"Lethal Pursuer", killerId:"nemesis", tags:["aura","early-game","info"] },
    { id:"deadlock", name:"Deadlock", killerId:"cenobite", tags:["generator","block","slowdown"] },
    { id:"hex-plaything", name:"Hex: Plaything", killerId:"cenobite", tags:["hex","hook","oblivious"] },
    { id:"scourge-hook-gift-of-pain", name:"Scourge Hook: Gift of Pain", killerId:"cenobite", tags:["scourge-hook","hook","slowdown"] },
    { id:"grim-embrace", name:"Grim Embrace", killerId:"artist", tags:["hook","generator","block"] },
    { id:"hex-pentimento", name:"Hex: Pentimento", killerId:"artist", tags:["hex","totem","slowdown"] },
    { id:"scourge-hook-pain-resonance", name:"Scourge Hook: Pain Resonance", killerId:"artist", tags:["scourge-hook","hook","regression"] },
    { id:"call-of-brine", name:"Call of Brine", killerId:"onryo", tags:["generator","regression","info"] },
    { id:"merciless-storm", name:"Merciless Storm", killerId:"onryo", tags:["generator","skill-check","block"] },
    { id:"scourge-hook-floods-of-rage", name:"Scourge Hook: Floods of Rage", killerId:"onryo", tags:["scourge-hook","aura","hook"] },
    { id:"darkness-revealed", name:"Darkness Revealed", killerId:"dredge", tags:["aura","locker","info"] },
    { id:"dissolution", name:"Dissolution", killerId:"dredge", tags:["chase","pallet","injury"] },
    { id:"septic-touch", name:"Septic Touch", killerId:"dredge", tags:["terror-radius","healing","exhaustion"] },
    { id:"awakened-awareness", name:"Awakened Awareness", killerId:"mastermind", tags:["aura","carry","info"] },
    { id:"superior-anatomy", name:"Superior Anatomy", killerId:"mastermind", tags:["chase","vault"] },
    { id:"terminus", name:"Terminus", killerId:"mastermind", tags:["endgame","injury","pressure"] },
    { id:"hex-face-the-darkness", name:"Hex: Face the Darkness", killerId:"knight", tags:["hex","info","scream"] },
    { id:"hubris", name:"Hubris", killerId:"knight", tags:["chase","stun","exposed"] },
    { id:"nowhere-to-hide", name:"Nowhere to Hide", killerId:"knight", tags:["generator","aura","info"] },
    { id:"game-afoot", name:"Game Afoot", killerId:"skull-merchant", tags:["obsession","chase","haste"] },
    { id:"leverage", name:"Leverage", killerId:"skull-merchant", tags:["hook","healing","slowdown"] },
    { id:"thwack", name:"THWACK!", killerId:"skull-merchant", tags:["break","info","scream"] },
    { id:"forced-hesitation", name:"Forced Hesitation", killerId:"singularity", tags:["down","slowdown","snowball"] },
    { id:"genetic-limits", name:"Genetic Limits", killerId:"singularity", tags:["healing","exhaustion","pressure"] },
    { id:"machine-learning", name:"Machine Learning", killerId:"singularity", tags:["generator","haste","stealth"] },
    { id:"alien-instinct", name:"Alien Instinct", killerId:"xenomorph", tags:["hook","tracking","stealth"] },
    { id:"rapid-brutality", name:"Rapid Brutality", killerId:"xenomorph", tags:["chase","haste","basic-attack"] },
    { id:"ultimate-weapon", name:"Ultimate Weapon", killerId:"xenomorph", tags:["locker","info","scream"] },
    { id:"batteries-included", name:"Batteries Included", killerId:"good-guy", tags:["generator","haste","endgame"] },
    { id:"friends-til-the-end", name:"Friends 'til the End", killerId:"good-guy", tags:["obsession","hook","exposed"] },
    { id:"hex-two-can-play", name:"Hex: Two Can Play", killerId:"good-guy", tags:["hex","stun","blindness"] },
    { id:"unbound", name:"Unbound", killerId:"unknown", tags:["chase","vault","haste"] },
    { id:"undone", name:"Undone", killerId:"unknown", tags:["generator","skill-check","regression"] },
    { id:"unforeseen", name:"Unforeseen", killerId:"unknown", tags:["generator","stealth","terror-radius"] },
    { id:"dark-arrogance", name:"Dark Arrogance", killerId:"lich", tags:["chase","vault","blindness"] },
    { id:"languid-touch", name:"Languid Touch", killerId:"lich", tags:["exhaustion","tracking","pressure"] },
    { id:"weave-attunement", name:"Weave Attunement", killerId:"lich", tags:["anti-item","aura","info"] },
    { id:"dominance", name:"Dominance", killerId:"dark-lord", tags:["totem","chest","block"] },
    { id:"hex-wretched-fate", name:"Hex: Wretched Fate", killerId:"dark-lord", tags:["hex","obsession","slowdown"] },
    { id:"human-greed", name:"Human Greed", killerId:"dark-lord", tags:["chest","aura","info"] },
    { id:"all-shaking-thunder", name:"All-Shaking Thunder", killerId:"houndmaster", tags:["chase","lunge"] },
    { id:"no-quarter", name:"No Quarter", killerId:"houndmaster", tags:["healing","skill-check","pressure"] },
    { id:"scourge-hook-jagged-compass", name:"Scourge Hook: Jagged Compass", killerId:"houndmaster", tags:["scourge-hook","hook","info"] },
    { id:"forever-entwined", name:"Forever Entwined", killerId:"ghoul", tags:["hook","carry","injury"] },
    { id:"hex-nothing-but-misery", name:"Hex: Nothing But Misery", killerId:"ghoul", tags:["hex","injury","slowdown"] },
    { id:"none-are-free", name:"None Are Free", killerId:"ghoul", tags:["endgame","hook","block"] },
    { id:"haywire", name:"Haywire", killerId:"animatronic", tags:["endgame","gate","regression"] },
    { id:"help-wanted", name:"Help Wanted", killerId:"animatronic", tags:["generator","chase","basic-attack"] },
    { id:"phantom-fear", name:"Phantom Fear", killerId:"animatronic", tags:["terror-radius","aura","scream"] },
    { id:"hex-overture-of-doom", name:"Hex: Overture of Doom", killerId:"krasue", tags:["hex","generator","stealth"] },
    { id:"ravenous", name:"Ravenous", killerId:"krasue", tags:["hook","exposed","pressure"] },
    { id:"wandering-eye", name:"Wandering Eye", killerId:"krasue", tags:["aura","injury","chase"] },
    { id:"hex-hive-mind", name:"Hex: Hive Mind", killerId:"first", tags:["hex","generator","regression"] },
    { id:"secret-project", name:"Secret Project", killerId:"first", tags:["totem","generator","block","stealth"] },
    { id:"turn-back-the-clock", name:"Turn Back the Clock", killerId:"first", tags:["hook","generator","regression"] },
    { id:"hex-scared-to-death", name:"Hex: Scared to Death", killerId:"slasher", tags:["hex","chase","pallet","slowdown"] },
    { id:"rampage", name:"Rampage", killerId:"slasher", tags:["chase","pallet","haste"] },
    { id:"silent-shadow", name:"Silent Shadow", killerId:"slasher", tags:["hook","stealth","endgame"] }
];
